-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
        args:
        - --no-markdown-linebreak-ext
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: v1.0.1
    hooks:
    -   id: remove-crlf
        exclude: npp/.*\.xml
    -   id: remove-tabs
-   repo: https://github.com/Lucas-C/pre-commit-hooks-java
    sha: v1.3.5
    hooks:
    -   id: validate-html
        files: ^docs/[^/]+\.html$
        args:
        - "--ignore=An \"img\" element must have an \"alt\" attribute"
